version: '2.2'
services:
  es79-01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: es710-01
    environment:
      - node.name=es710-01
      - cluster.name=es-docker-cluster-710
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/dv/elastic/elastic79/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic710

  kib79-01:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kib710-01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es710-01:9200
      ELASTICSEARCH_HOSTS: http://es710-01:9200
    networks:
      - elastic710

volumes:
  data01:
    driver: local

networks:
  elastic710:
    driver: bridge
